- type: entity
  id: ShredderMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: shredder machine board
  description: A machine printed circuit board for a shredder.
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: Shredder
      requirements:
        MatterBin: 1
      materialRequirements:
        Glass: 1
    - type: StaticPrice
      price: 100

- type: entity
  parent: BaseComputerCircuitboard
  id: ShuttleIDComputerCircuitboard
  name: Shuttle ID card computer board
  description: A computer printed circuit board for a shuttle-specific ID card console.
  components:
  - type: Sprite
    state: cpu_command
  - type: ComputerBoard
    prototype: ComputerShuttleIdConsole
  - type: StaticPrice
    price: 750
  - type: Tag
    tags:
    - DroneUsable
